import type { Metadata } from 'next';
import { Playfair_Display, Space_Mono, Fjalla_One } from 'next/font/google';
import './globals.css';
import { SiteHeader } from '@/components/site-header';

const sans = Fjalla_One({
  variable: '--font-sans',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

const serif = Playfair_Display({
  variable: '--font-serif',
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  display: 'swap',
});

const mono = Space_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          // Prevent theme flash on first paint
          dangerouslySetInnerHTML={{
            __html: `(() => { try { const ls = localStorage.getItem('theme'); const m = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; const dark = ls ? ls === 'dark' : m; const root = document.documentElement; dark ? root.classList.add('dark') : root.classList.remove('dark'); } catch (_) {} })();`,
          }}
        />
      </head>
      <body
        className={`${sans.variable} ${serif.variable} ${mono.variable} antialiased`}
      >
        <SiteHeader />
        <main className="mx-auto w-full max-w-5xl px-4">{children}</main>
      </body>
    </html>
  );
}
