import { TeamMemberApi } from './api-types';

// Mock data for development - using API model structure
export const mockTeamMembersApi: TeamMemberApi[] = [
  // Main squad - Spelerskern
  {
    id: 1,
    name: 'Robin Pellegrims',
    jersey_number: 10,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: ['kapitein'],
    join_date: '2015-09-01',
  },
  {
    id: 2,
    name: 'Tom De Baets',
    jersey_number: 7,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: ['voorzitter'],
    join_date: '2014-08-15',
  },
  {
    id: 3,
    name: 'Bart Claes',
    jersey_number: 1,
    position: 'doelman',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: null,
    join_date: '2016-01-10',
  },
  {
    id: 4,
    name: 'Stef Van Hoof',
    jersey_number: 5,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: ['ondervoorzitter'],
    join_date: '2015-03-20',
  },
  {
    id: 5,
    name: 'Koen Hermans',
    jersey_number: 11,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: null,
    join_date: '2017-09-05',
  },
  {
    id: 6,
    name: 'Wim Goossens',
    jersey_number: 8,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: ['penningmeester'],
    join_date: '2014-10-12',
  },
  {
    id: 7,
    name: 'Peter Claes',
    jersey_number: 3,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: null,
    join_date: '2018-02-14',
  },
  {
    id: 8,
    name: 'Jan Peeters',
    jersey_number: 9,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
    functions: null,
    join_date: '2019-06-01',
  },
  // Reserve squad - Reserves
  {
    id: 9,
    name: 'Mark Janssens',
    jersey_number: 12,
    position: 'doelman',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
    functions: null,
    join_date: '2020-01-15',
  },
  {
    id: 10,
    name: 'Kevin Vermeulen',
    jersey_number: 14,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
    functions: null,
    join_date: '2021-03-10',
  },
  {
    id: 11,
    name: 'Luc Wouters',
    jersey_number: 15,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
    functions: null,
    join_date: '2020-09-22',
  },
  {
    id: 12,
    name: 'Steven Maes',
    jersey_number: 16,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
    functions: null,
    join_date: '2022-02-05',
  },
  {
    id: 13,
    name: 'Frank Mertens',
    jersey_number: 17,
    position: 'veldspeler',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
    functions: null,
    join_date: '2021-08-18',
  },
];
