import { TeamMember } from '@/components/player-card';

// Mock data for development
export const mockTeamMembers: TeamMember[] = [
  // Main squad - Spelerskern
  {
    id: 1,
    name: 'Robin Pellegrims',
    number: 10,
    position: 'Aanvaller',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 2,
    name: 'Tom De Baets',
    number: 7,
    position: 'Middenvelder',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 3,
    name: 'Bart Claes',
    number: 1,
    position: 'Doelman',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 4,
    name: 'Stef Van Hoof',
    number: 5,
    position: 'Verdediger',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 5,
    name: 'Koen Hermans',
    number: 11,
    position: 'Aanvaller',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 6,
    name: 'Wim Goossens',
    number: 8,
    position: 'Middenvelder',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 7,
    name: 'Peter Claes',
    number: 3,
    position: 'Verdediger',
    role: 'Speler',
    squad: 'main',
  },
  {
    id: 8,
    name: 'Jan Peeters',
    number: 9,
    position: 'Aanvaller',
    role: 'Speler',
    squad: 'main',
  },
  // Reserve squad - Reserves
  {
    id: 9,
    name: 'Mark Janssens',
    number: 12,
    position: 'Doelman',
    role: 'Speler',
    squad: 'reserve',
  },
  {
    id: 10,
    name: 'Kevin Vermeulen',
    number: 14,
    position: 'Verdediger',
    role: 'Speler',
    squad: 'reserve',
  },
  {
    id: 11,
    name: 'Luc Wouters',
    number: 15,
    position: 'Middenvelder',
    role: 'Speler',
    squad: 'reserve',
  },
  {
    id: 12,
    name: 'Steven Maes',
    number: 16,
    position: 'Aanvaller',
    role: 'Speler',
    squad: 'reserve',
  },
  {
    id: 13,
    name: 'Frank Mertens',
    number: 17,
    position: 'Verdediger',
    role: 'Speler',
    squad: 'reserve',
  },
];
