import { TeamMemberApi } from './api-types';

// Mock data for development - using API model structure
export const mockTeamMembersApi: TeamMemberApi[] = [
  // Main squad - Spelerskern
  {
    id: 1,
    name: 'Robin Pellegrims',
    jersey_number: 10,
    position: 'Aanvaller',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 2,
    name: 'Tom De Baets',
    jersey_number: 7,
    position: 'Middenvelder',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 3,
    name: 'Bart Claes',
    jersey_number: 1,
    position: 'Doelman',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 4,
    name: 'Stef Van Hoof',
    jersey_number: 5,
    position: 'Verdediger',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 5,
    name: 'Koen Hermans',
    jersey_number: 11,
    position: 'Aanvaller',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 6,
    name: 'Wim Goossens',
    jersey_number: 8,
    position: 'Middenvelder',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 7,
    name: 'Peter Claes',
    jersey_number: 3,
    position: 'Verdediger',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  {
    id: 8,
    name: 'Jan Peeters',
    jersey_number: 9,
    position: 'Aanvaller',
    role: 'Speler',
    squad_type: 'main',
    photo_url: null,
  },
  // Reserve squad - Reserves
  {
    id: 9,
    name: 'Mark Janssens',
    jersey_number: 12,
    position: 'Doelman',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
  },
  {
    id: 10,
    name: 'Kevin Vermeulen',
    jersey_number: 14,
    position: 'Verdediger',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
  },
  {
    id: 11,
    name: 'Luc Wouters',
    jersey_number: 15,
    position: 'Middenvelder',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
  },
  {
    id: 12,
    name: 'Steven Maes',
    jersey_number: 16,
    position: 'Aanvaller',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
  },
  {
    id: 13,
    name: 'Frank Mertens',
    jersey_number: 17,
    position: 'Verdediger',
    role: 'Speler',
    squad_type: 'reserve',
    photo_url: null,
  },
];
