#!/usr/bin/env sh

# Get all staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|mjs|cjs,json|css|md)$' || true)

if [ -n "$STAGED_FILES" ]; then
  # Run prettier on staged files
  npx prettier --write $STAGED_FILES

  # Re-add the formatted files
  git add $STAGED_FILES
fi
